version: '3.7'

services:
  frontend:
    container_name: vue-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5173:5173'
