services:
  api:
    build:
      context: .
    develop:
      watch:
        - action: rebuild
          path: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      influx:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      backend:
        ipv4_address: 10.0.0.4
      frontend:
  mysql:
    image: mysql
    restart: always
    ports:
      - 8080:3306
    volumes:
      - slow-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123
      - MYSQL_DATABASE=Heat Variant
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Admin123
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      backend:
        ipv4_address: 10.0.0.3
      frontend:
  influx:
    image: influxdb:2
    restart: always
    ports:
      - 8086:8086
    volumes:
      - fast-db:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=Admin123
      - DOCKER_INFLUXDB_INIT_PASSWORD=Admin123
      - DOCKER_INFLUXDB_INIT_ORG=heat_variant
      - DOCKER_INFLUXDB_INIT_BUCKET=variant
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 3s
      timeout: 10s
      retries: 5
    networks:
      backend:
        ipv4_address: 10.0.0.2
volumes:
  slow-db:
  fast-db:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/28
          gateway: 10.0.0.1
  frontend:
    driver: bridge
