services:
  api:
    build:
      context: .
    develop:
      watch:
        - action: rebuild
          path: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      backend:
        ipv4_address: 10.0.0.3
      frontend:
  db:
    image: influxdb:2
    restart: always
    ports:
      - 8086:8086
    volumes:
      - db-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=Admin123
      - DOCKER_INFLUXDB_INIT_PASSWORD=Admin123
      - DOCKER_INFLUXDB_INIT_ORG=heat_variant
      - DOCKER_INFLUXDB_INIT_BUCKET=variant
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 3s
      timeout: 10s
      retries: 5
    networks:
      backend:
        ipv4_address: 10.0.0.2

volumes:
  db-data:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1
  frontend:
    driver: bridge
